services:
  scraper:
    build: ./scraper
    container_name: scraper
    restart: unless-stopped
    shm_size: 2g
    environment:
      - SE_OFFLINE="true"
    networks:
      - kafka-net
      - scraper-net
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    env_file:
      - ./scraper/.env

  builder:
    build: ./builder
    container_name: builder
    restart: unless-stopped
    networks:
      - builder-net
      - kafka-net
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      SERVERS: '["kafka-1:19092", "kafka-2:19093", "kafka-3:19094"]'

  frontend:
    build:
      context: ./frontend
      target: dev
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    networks:
      - app-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_URL: db
      SERVERS: '["kafka-1:19092", "kafka-2:19093", "kafka-3:19094"]'
    ports:
      - "9000:9000"
    networks:
      - app-net
      - db-net
    depends_on:
      - db

  db:
    image: timescale/timescaledb:latest-pg17
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "dbvol:/dev/shm"
    networks:
      - db-net
      - kafka-net
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-net

  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-1
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka-1:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:29092,2@kafka-2:29092,3@kafka-3:29092
      CLUSTER_ID: "q1Sh-7qfT3S8zG8zYb9m2w"
    volumes:
      - kafka-data1:/var/lib/kafka/data

  kafka-2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-2
    networks:
      - kafka-net
    ports:
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://kafka-2:19093,EXTERNAL://0.0.0.0:9093,CONTROLLER://kafka-2:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:19093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:29092,2@kafka-2:29092,3@kafka-3:29092
      CLUSTER_ID: "q1Sh-7qfT3S8zG8zYb9m2w"
    volumes:
      - kafka-data2:/var/lib/kafka/data

  kafka-3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-3
    networks:
      - kafka-net
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://kafka-3:19094,EXTERNAL://0.0.0.0:9094,CONTROLLER://kafka-3:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:19094,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:29092,2@kafka-2:29092,3@kafka-3:29092
      CLUSTER_ID: "q1Sh-7qfT3S8zG8zYb9m2w"
    volumes:
      - kafka-data3:/var/lib/kafka/data

  kafka-connect:
    build: ./kafkaConnect
    container_name: kafka-connect
    networks:
      - kafka-net
      - db-net
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka-1:19092,kafka-2:19093,kafka-3:19094"
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_GROUP_ID: "kafka-connect-group"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "true"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "true"
      CONNECT_PLUGIN_PATH: "/usr/share/confluent-hub-components"
      CONNECT_JDBC_CONNECTION_URL: "jdbc:postgresql://db:5432/${DB_NAME}"
      CONNECT_JDBC_USERNAME: "${DB_USER}"
      CONNECT_JDBC_PASSWORD: "${DB_PASSWORD}"
      CONNECTOR_CONFIG_DIR: "/etc/kafka-connect/connectors"
    entrypoint: ["/etc/kafka-connect/connectors/entrypoint.sh"]
    volumes:
      - ./kafkaConnect:/etc/kafka-connect/connectors
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - db



volumes:
  dbvol:
  kafka-data1:
  kafka-data2:
  kafka-data3:

networks:
  app-net:
    driver: bridge
  kafka-net:
    driver: bridge
  scraper-net:
    driver: bridge
  builder-net:
    driver: bridge
  db-net:
    driver: bridge
