FROM confluentinc/cp-kafka-connect:7.6.1

# Installation du JDBC Sink Connector depuis Confluent Hub
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest

# Optionnel : drivers JDBC PostgreSQL
RUN wget https://jdbc.postgresql.org/download/postgresql-42.7.4.jar -P /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib/
